### PR TITLE
Writing Readme.md for tutorial to learning Javascript

### PR DESCRIPTION
**Pull request by amirudev**
Hello, I was making readme.md more useful for junior developer to learn javascript

### CODE REVIEW

**Comment by amirudev** [comment]
Hello i was made tutorials for javascript, I recommending to put this after Algorithm section, hope this make your repository better ^^ Lets make the repository together !

**Comment by avsingh999** [comment]
Hi @wahyuamirulloh 
The Readme.md file only contains information with linked files about what is in this repo.So Please Don't add code in this file

**Comment by avsingh999** [comment]
> Hello i was made tutorials for javascript, I recommending to put this after Algorithm section, hope this make your repository better ^^ Lets make the repository together !

Sure I like it ❤️ 😍

**Comment by avsingh999** [comment]
Please go Ahead

**Comment by amirudev** [comment]
please merge my branch T_T

**Comment by amirudev** [comment]
I Have write a lot, please merge my branch T_T

**Comment by amirudev** [comment]
I made tutorial.js please merge that T_T

**Pull request merged**
